FROM centos:latest
MAINTAINER doc.yhong39.ops
COPY index.html /var/www/html/
CMD ["/bin/bash"]
LABEL version=1.0
LABEL description="My first Image"
LABEL maintainer="yhong39@myseneca.ca"
EXPOSE 80/tcp
